import { useState } from "react";
import { AddRounded, EditOutlined, EventAvailableOutlined, PrintOutlined } from "@mui/icons-material";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Stack, Tab, Tabs, Typography, useMediaQuery, useTheme } from "@mui/material";
import type { MonitoringProgram } from "../../services/monitoringPrograms";
import type { Household } from "../../types";
import type { RegistryInhabitant } from "../../services/inhabitantModel";
import { todayInManila } from "../../services/inhabitantModel";
import { activities, dateLabel, isRecorded, nextDue, type ChangeEntry, type MonitoringActivity, type MonitoringCase } from "../../services/monitoringModel";
import { printMonitoring } from "../../utils/monitoringExport";
import { ActivityForm, CaseForm } from "./MonitoringForms";
export function MonitoringStatus({status,late=false}:{status:string;late?:boolean}) {return <Chip className="mr-status" size="small" variant="outlined" color={late?"error":status==="Done"||status==="Completed"?"success":status==="Referred"?"info":status==="Pending"?"warning":"default"} label={late?"Overdue":status} />;}
function Field({label,value}:{label:string;value?:string}){return <div><dt>{label}</dt><dd>{value||"Not recorded"}</dd></div>;}
const labels:Record<string,string>={program:"Program",condition:"Condition / focus",assignedTo:"Assigned staff",startDate:"Start date",notes:"Case notes",status:"Status",completedDate:"Completion date",closureNotes:"Completion result",scheduledDate:"Scheduled date",actualDate:"Actual date",activityType:"Activity",attendance:"Attendance",observations:"Observations",result:"Result",actionTaken:"Action taken",referredTo:"Referred to",referralReason:"Referral reason"};
function Changes({entry}:{entry:ChangeEntry}){
  const before=(entry.before||{}) as unknown as Record<string,unknown>,after=entry.after as unknown as Record<string,unknown>;
  return <details className="mr-change"><summary><strong>{entry.action}</strong><span>{new Date(entry.at).toLocaleString("en-PH",{timeZone:"Asia/Manila"})} · {entry.actorName||entry.by}</span></summary>{entry.reason&&<Typography variant="body2" sx={{mt:1}}>Reason: {entry.reason}</Typography>}<dl className="mr-change-list">{Object.entries(labels).filter(([key])=>after[key]!==undefined&&before[key]!==after[key]).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{before[key]!==undefined&&<span className="mr-old-value">Previous: {String(before[key]||"Not recorded")}</span>}<span>Saved: {String(after[key]||"Not recorded")}</span></dd></div>)}</dl>{entry.action==="Case completed"&&Boolean(entry.affectedActivityIds?.length)&&<Typography variant="body2">{entry.affectedActivityIds.length} pending followup(s) cancelled with this completion.</Typography>}</details>;
}
export default function MonitoringDetails({record,cases,people,households,programs,onClose,onOpenCase}:{record:MonitoringCase;programs:MonitoringProgram[];cases:MonitoringCase[];people:RegistryInhabitant[];households:Household[];onClose:()=>void;onOpenCase:(id:string)=>void}) {
  const [tab,setTab]=useState(0),[error,setError]=useState("");
  const [form,setForm]=useState<null|{kind:"case"}|{kind:"activity";activity?:MonitoringActivity;mode:"Pending"|"Done"|"Referred"|"Cancelled"}>(null);
  const fullScreen=useMediaQuery(useTheme().breakpoints.down("sm"));
  const visits=activities(record).sort((a,b)=>(b.actualDate||b.scheduledDate).localeCompare(a.actualDate||a.scheduledDate)||b.updatedAt-a.updatedAt);
  const related=cases.filter(c=>(record.scope==="household"?c.scope==="household"&&c.householdId===record.householdId:c.scope!=="household"&&c.inhabitantId===record.inhabitantId)&&c.id!==record.id);
  if(form?.kind==="case")return <CaseForm programs={programs} record={record} people={people} households={households} cases={cases} onClose={()=>setForm(null)} onSaved={()=>setForm(null)} />;
  if(form?.kind==="activity")return <ActivityForm record={record} activity={form.activity} mode={form.mode} onClose={()=>setForm(null)} onSaved={()=>setForm(null)} />;
  return <Dialog open onClose={onClose} maxWidth="lg" fullWidth fullScreen={fullScreen} className="mr-dialog" aria-labelledby="mr-case-title"><DialogTitle id="mr-case-title"><Stack direction="row" spacing={2} alignItems="center" justifyContent="space-between"><Box>{record.person.fullName}<Typography component="span" display="block" variant="body2">{record.program} · {record.condition||"General monitoring"}</Typography></Box><MonitoringStatus status={record.status} /></Stack></DialogTitle>
    <Tabs value={tab} onChange={(_,next:number)=>setTab(next)} variant="scrollable" scrollButtons="auto" className="mr-detail-tabs" aria-label="Monitoring case sections"><Tab label="Overview & activities" /><Tab label={`Change history (${Object.keys(record.history||{}).length})`} /></Tabs>
    <DialogContent dividers>{error&&<Alert severity="warning" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
      {tab===0?<><div className="mr-case-actions"><Button variant="contained" startIcon={<EventAvailableOutlined />} disabled={record.status==="Completed"} onClick={()=>setForm({kind:"activity",mode:"Done"})}>Record activity</Button><Button variant="outlined" startIcon={<AddRounded />} disabled={record.status==="Completed"} onClick={()=>setForm({kind:"activity",mode:"Pending"})}>Schedule followup</Button><Button startIcon={<EditOutlined />} onClick={()=>setForm({kind:"case"})}>Edit case</Button><Button startIcon={<PrintOutlined />} onClick={()=>setError(printMonitoring("history",[record],visits.map(activity=>({record,activity})),[record.program,"All activity dates"],todayInManila())?"":"Allow popups for this page, then select Print history again.")}>Print history</Button></div>
        {record.status==="Completed"&&<Alert severity="success" sx={{mt:2}}>Completed {dateLabel(record.completedDate)}. {record.closureNotes}</Alert>}
        <dl className="mr-details-grid"><Field label="Assigned staff" value={record.assignedTo} /><Field label="Case started" value={dateLabel(record.startDate)} /><Field label="Next pending followup" value={nextDue(record)?dateLabel(nextDue(record)):"None scheduled"} /><Field label="Latest recorded activity" value={visits.find(isRecorded)?.actualDate?dateLabel(visits.find(isRecorded)!.actualDate):"No activity recorded"} /><Field label="Household at enrollment" value={record.person.householdName} /><Field label="Location at enrollment" value={[record.person.purok,record.person.address].filter(Boolean).join(" · ")} /><Field label="Case notes" value={record.notes} />{record.scope==="household"&&<Field label="Covered members at enrollment" value={Object.values(record.participants||{}).map(p=>p.fullName).join(", ")} />}</dl>
        <div className="mr-section-heading"><Typography component="h3">Activity history</Typography><Typography variant="body2">{visits.length} activity record(s)</Typography></div>
        <Stack spacing={2}>{visits.map(a=><article className="mr-activity" key={a.id}><div className="mr-activity-heading"><Box><Typography component="h4">{a.activityType}</Typography><Typography variant="body2">Scheduled {dateLabel(a.scheduledDate)}{a.actualDate?` · Recorded ${dateLabel(a.actualDate)}`:""}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><MonitoringStatus status={a.status} late={a.status==="Pending"&&record.status!=="Completed"&&a.scheduledDate<todayInManila()} />{record.status!=="Completed"&&<Button size="small" onClick={()=>setForm({kind:"activity",activity:a,mode:a.status==="Pending"?"Done":a.status})}>{a.status==="Pending"?"Record visit":"Edit activity"}</Button>}</Stack></div>
          {isRecorded(a)&&<><dl className="mr-details-grid mr-activity-details"><Field label="Attendance" value={a.attendance} /><Field label="Staff on activity record" value={a.context.assignedTo} /><Field label="Observations" value={a.observations} /><Field label="Result" value={a.result} /><Field label="Action taken" value={a.actionTaken} />{a.status==="Referred"&&<><Field label="Referred to" value={a.referredTo} /><Field label="Referral reason" value={a.referralReason} /></>}</dl></>}
          {a.status==="Pending"&&record.status!=="Completed"&&<Button size="small" onClick={()=>setForm({kind:"activity",activity:a,mode:"Pending"})}>Edit schedule or cancel</Button>}
        </article>)}</Stack>
        {related.length>0&&<Box sx={{mt:3}}><Typography component="h3">Other cases for this {record.scope==="household"?"household":"inhabitant"}</Typography><div className="mr-related">{related.map(c=><Button key={c.id} variant="outlined" onClick={()=>onOpenCase(c.id)}>{c.program} · {c.status} · {dateLabel(c.startDate)}</Button>)}</div></Box>}
      </>:<Stack spacing={1.5}>{Object.values(record.history||{}).sort((a,b)=>b.at-a.at).map(entry=><Changes key={entry.id} entry={entry} />)}</Stack>}
    </DialogContent><DialogActions><Typography variant="caption" sx={{flex:1,overflowWrap:"anywhere"}}>Case {record.id}</Typography><Button onClick={onClose}>Close</Button></DialogActions>
  </Dialog>;
}
