import { useEffect, useMemo, useState } from "react";
import { AddRounded, CheckCircleOutlineRounded, DownloadRounded, EventNoteOutlined, FilterAltOutlined, TuneRounded, PeopleAltOutlined, PrintOutlined, RefreshRounded, SearchRounded, WarningAmberOutlined } from "@mui/icons-material";
import { Alert, Autocomplete, Box, Button, Chip, Collapse, InputAdornment, LinearProgress, MenuItem, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, Tabs, TextField, Typography } from "@mui/material";
import type { Household } from "../types";
import { BUNUANAN_PUROKS } from "../config/bunuananServiceArea";
import { todayInManila, validDate, type RegistryInhabitant } from "../services/inhabitantModel";
import { listenHouseholds, listenInhabitants } from "../services/inhabitantService";
import { householdKey, isHouseholdCase, ACTIVITY_STATUSES, CASE_STATUSES, DEFAULT_MONITORING_FILTERS, activityRows, dateLabel, filterActivities, filterCases, nextDue, overdue, pending, periodRange, reportGroups, reportTotals, wasMonitored, type ActivityRow, type MonitoringCase, type MonitoringFilters } from "../services/monitoringModel";
import { listenMonitoringCases } from "../services/monitoringService";
import { downloadMonitoringCsv, filterDescription, printMonitoring, type MonitoringView } from "../utils/monitoringExport";
import MonitoringDetails, { MonitoringStatus } from "../components/monitoring/MonitoringDetails";
import { ActivityForm } from "../components/monitoring/MonitoringForms";
import MonitoringEnrollment from "../components/monitoring/MonitoringEnrollment";
import MonitoringProgramCatalog from "../components/monitoring/MonitoringProgramCatalog";
import { listenMonitoringPrograms } from "../services/monitoringProgramService";
import type { MonitoringProgram } from "../services/monitoringPrograms";
import "../styles/monitoring.css";

export default function MonitoringReports() {
  const [catalogPrograms,setCatalogPrograms]=useState<MonitoringProgram[]>([]),[catalogOpen,setCatalogOpen]=useState(false);
  const [cases,setCases]=useState<MonitoringCase[]>([]),[people,setPeople]=useState<RegistryInhabitant[]>([]),[households,setHouseholds]=useState<Household[]>([]);
  const [loaded,setLoaded]=useState({cases:false,people:false,households:false,programs:false}),[error,setError]=useState(""),[printError,setPrintError]=useState(""),[notice,setNotice]=useState(""),[retry,setRetry]=useState(0);
  const [view,setView]=useState<MonitoringView>("followups"),[filters,setFilters]=useState<MonitoringFilters>({...DEFAULT_MONITORING_FILTERS,status:"Pending"}),[period,setPeriod]=useState("all"),[advanced,setAdvanced]=useState(false);
  const [page,setPage]=useState(0),[pageSize,setPageSize]=useState(10),[newCase,setNewCase]=useState(false),[selected,setSelected]=useState("");
  const [recordVisit,setRecordVisit]=useState<ActivityRow|null>(null),[today,setToday]=useState(todayInManila);
  useEffect(()=>{const timer=window.setInterval(()=>setToday(todayInManila()),60000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{if(period==="month"||period==="quarter")setFilters(f=>({...f,...periodRange(period,today)}));},[today,period]);
  useEffect(()=>{
    let active=true;setLoaded({cases:false,people:false,households:false,programs:false});setError("");
    const failed=(e:Error)=>{if(active){setError(`Unable to load monitoring records: ${e.message}`);setCases([]);setPeople([]);setHouseholds([]);setCatalogPrograms([]);}};
    const stops=[listenMonitoringPrograms(items=>{if(active){setCatalogPrograms(items);setLoaded(l=>({...l,programs:true}));}},failed),listenMonitoringCases(items=>{if(active){setCases(items);setLoaded(l=>({...l,cases:true}));}},failed),listenInhabitants(items=>{if(active){setPeople(items);setLoaded(l=>({...l,people:true}));}},failed),listenHouseholds(items=>{if(active){setHouseholds(items);setLoaded(l=>({...l,households:true}));}},failed)];
    return()=>{active=false;stops.forEach(stop=>stop());};
  },[retry]);
  const ready=loaded.cases&&loaded.people&&loaded.households&&loaded.programs&&!error;
  const rows=useMemo(()=>activityRows(cases),[cases]);
  const allContexts=useMemo(()=>[...cases.map(c=>({program:c.program,condition:c.condition,assignedTo:c.assignedTo})),...rows.map(r=>r.activity.context)],[cases,rows]);
  const programs=[...new Set(allContexts.map(c=>c.program).filter(Boolean))].sort(),conditions=[...new Set(allContexts.map(c=>c.condition).filter(Boolean))].sort(),staff=[...new Set(allContexts.map(c=>c.assignedTo).filter(Boolean))].sort();
  const rangeError=Boolean(filters.from&&!validDate(filters.from)||filters.to&&!validDate(filters.to)||filters.from&&filters.to&&filters.from>filters.to);
  const shownCases=useMemo(()=>rangeError?[]:filterCases(cases,filters),[cases,filters,rangeError]);
  const shownRows=useMemo(()=>rangeError?[]:filterActivities(cases,filters,view==="reports",today),[cases,filters,view,today,rangeError]);
  const count=view==="cases"?shownCases.length:shownRows.length,safePage=Math.min(page,Math.max(0,Math.ceil(count/pageSize)-1)),start=safePage*pageSize;
  const selectedCase=cases.find(c=>c.id===selected),currentVisitCase=recordVisit?cases.find(c=>c.id===recordVisit.record.id):null;
  const totals=reportTotals(shownRows),groups=reportGroups(shownRows);
  const overview=[{label:"Inhabitants monitored",value:new Set(rows.filter(r=>wasMonitored(r.activity)&&!isHouseholdCase(r.record)).map(r=>r.record.inhabitantId)).size,note:"With recorded followup results",icon:<PeopleAltOutlined />},{label:"Pending followups",value:cases.reduce((sum,c)=>sum+pending(c).length,0),note:"Awaiting an activity result",icon:<EventNoteOutlined />},{label:"Overdue followups",value:rows.filter(r=>overdue(r,today)).length,note:"Scheduled before today",icon:<WarningAmberOutlined />},{label:"Completed cases",value:cases.filter(c=>c.status==="Completed").length,note:"Monitoring cases currently closed",icon:<CheckCircleOutlineRounded />}];
  function change<K extends keyof MonitoringFilters>(key:K,value:MonitoringFilters[K]){setFilters(f=>({...f,[key]:value}));setPage(0);}
  function choosePeriod(value:string){setPeriod(value);if(value!=="custom")setFilters(f=>({...f,...periodRange(value,today)}));setPage(0);}
  function switchView(next:MonitoringView){setView(next);setPage(0);setPrintError("");setPeriod(next==="reports"?"month":"all");setFilters(f=>({...f,status:next==="followups"?"Pending":"",...periodRange(next==="reports"?"month":"all",today),sort:next==="reports"?"newest":"due",dateBasis:next==="reports"?"actual":"scheduled"}));}
  function reset(){setFilters({...DEFAULT_MONITORING_FILTERS,status:view==="followups"?"Pending":"",sort:view==="reports"?"newest":"due",...periodRange(view==="reports"?"month":"all",today)});setPeriod(view==="reports"?"month":"all");setPage(0);}
  const householdChoices=[...new Map(cases.filter(c=>householdKey(c.person)).map(c=>[householdKey(c.person),{id:householdKey(c.person),label:c.person.householdName+(c.person.householdId?"":" (earlier record)")}])).values()].sort((a,b)=>a.label.localeCompare(b.label));
  const memberChoices=[...new Map(cases.flatMap(c=>c.scope==="household"?Object.entries(c.participants||{}).map(([id,p])=>({id,label:p.fullName})): [{id:c.inhabitantId,label:c.person.fullName}]).map(p=>[p.id,p])).values()].sort((a,b)=>a.label.localeCompare(b.label));
  const scope=filterDescription(filters,view,householdChoices.find(h=>h.id===filters.household)?.label,memberChoices.find(p=>p.id===filters.member)?.label),chips=(["search","program","condition","purok","staff","status","household","member","scope"] as const).filter(key=>filters[key]).map(key=>({key,label:key==="household"?`Household: ${householdChoices.find(h=>h.id===filters.household)?.label||filters.household}`:key==="member"?`Member: ${memberChoices.find(p=>p.id===filters.member)?.label||filters.member}`:key==="scope"?`Scope: ${filters.scope==="household"?"Household":"Individual"}`:key==="status"?`Status: ${filters[key]}`:filters[key]}));
  return <div className="mr-page"><header className="mr-header"><div><div className="mr-eyebrow">COMMUNITY FOLLOWUP</div><Typography component="h1" variant="h4">Monitoring reports</Typography><Typography color="text.secondary">Track scheduled visits, record results, and see who needs followup.</Typography></div><div className="mr-actions"><Button startIcon={<TuneRounded />} disabled={!ready} onClick={()=>setCatalogOpen(true)}>Manage programs</Button><Button variant="contained" startIcon={<AddRounded />} disabled={!ready} onClick={()=>setNewCase(true)}>Add monitoring</Button></div></header>
    {notice&&<Alert severity="success" onClose={()=>setNotice("")}>{notice}</Alert>}
    {error&&<Alert severity="error" action={<Button color="inherit" startIcon={<RefreshRounded />} onClick={()=>setRetry(v=>v+1)}>Retry</Button>}>{error}</Alert>}
    {printError&&<Alert severity="warning" onClose={()=>setPrintError("")}>{printError}</Alert>}
    <div className="mr-overview-label"><Typography variant="body2">Across all monitoring records</Typography><Typography variant="body2">As of {dateLabel(today)}</Typography></div>
    <div className="mr-stats" aria-busy={!ready}>{overview.map((stat,i)=><div className={`mr-stat mr-stat-${i}`} key={stat.label}><span className="mr-stat-icon">{stat.icon}</span><div><span>{stat.label}</span><strong>{ready?stat.value.toLocaleString():"—"}</strong><small>{stat.note}</small></div></div>)}</div>
    <section className="mr-workspace"><Tabs value={view} onChange={(_,next:MonitoringView)=>switchView(next)} variant="scrollable" scrollButtons="auto" className="mr-tabs" aria-label="Monitoring views"><Tab value="followups" label="Followup queue" id="mr-followups-tab" aria-controls="mr-panel" /><Tab value="cases" label="Monitoring cases" id="mr-cases-tab" aria-controls="mr-panel" /><Tab value="reports" label="Monthly & quarterly reports" id="mr-reports-tab" aria-controls="mr-panel" /></Tabs>
      {!ready&&!error&&<Box sx={{p:3}} role="status"><LinearProgress /><Typography sx={{mt:2}}>Loading monitoring records…</Typography></Box>}
      {ready&&<div role="tabpanel" id="mr-panel" aria-labelledby={`mr-${view}-tab`}><div className="mr-filter-area"><div className="mr-main-filters">
        <TextField label="Search monitoring" placeholder="Name, program or case ID" value={filters.search} onChange={e=>change("search",e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchRounded /></InputAdornment>}} />
        <TextField select label="Program filter" value={filters.program} onChange={e=>change("program",e.target.value)}><MenuItem value="">All programs</MenuItem>{programs.map(p=><MenuItem value={p} key={p}>{p}</MenuItem>)}</TextField>
        <TextField select label="Status filter" value={filters.status} onChange={e=>change("status",e.target.value)}><MenuItem value="">All statuses</MenuItem>{(view==="cases"?CASE_STATUSES:view==="reports"?["Done","Referred"]:[...ACTIVITY_STATUSES,"Overdue"]).map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField>
        <TextField select label="Period" value={period} onChange={e=>choosePeriod(e.target.value)}><MenuItem value="all">All dates</MenuItem><MenuItem value="month">This month</MenuItem><MenuItem value="quarter">This quarter</MenuItem><MenuItem value="custom">Custom dates</MenuItem></TextField>
      </div><div className="mr-period-row">{period!=="all"&&<><TextField label="From date" type="date" InputLabelProps={{shrink:true}} value={filters.from} onChange={e=>{setPeriod("custom");change("from",e.target.value);}} /><TextField label="To date" type="date" InputLabelProps={{shrink:true}} value={filters.to} onChange={e=>{setPeriod("custom");change("to",e.target.value);}} /></>}{view==="followups"?<TextField select label="Filter dates by" value={filters.dateBasis} onChange={e=>change("dateBasis",e.target.value as "scheduled"|"actual")}><MenuItem value="scheduled">Scheduled date</MenuItem><MenuItem value="actual">Actual activity date</MenuItem></TextField>:<Typography variant="body2">{view==="cases"?"Period filters the case start date.":"Reports use actual activity dates, including earlier entries recorded later."}</Typography>}<Button startIcon={<FilterAltOutlined />} onClick={()=>setAdvanced(v=>!v)} aria-expanded={advanced} aria-controls="mr-extra-filters">More filters</Button></div>
      <Collapse in={advanced}><div id="mr-extra-filters" className="mr-extra-filters"><Autocomplete options={householdChoices} value={householdChoices.find(h=>h.id===filters.household)||null} getOptionLabel={h=>h.label} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,h)=>change("household",h?.id||"")} renderInput={params=><TextField {...params} label="Household filter" />} /><Autocomplete options={memberChoices} value={memberChoices.find(p=>p.id===filters.member)||null} getOptionLabel={p=>p.label} isOptionEqualToValue={(a,b)=>a.id===b.id} onChange={(_,p)=>change("member",p?.id||"")} renderInput={params=><TextField {...params} label="Member filter" />} /><TextField select label="Monitoring scope" value={filters.scope||""} onChange={e=>change("scope",e.target.value)}><MenuItem value="">All cases</MenuItem><MenuItem value="person">Individual programs</MenuItem><MenuItem value="household">Household activities</MenuItem></TextField><TextField select label="Purok filter" value={filters.purok} onChange={e=>change("purok",e.target.value)}><MenuItem value="">All Puroks</MenuItem>{BUNUANAN_PUROKS.map(p=><MenuItem key={p} value={p}>{p}</MenuItem>)}</TextField><TextField select label="Condition filter" value={filters.condition} onChange={e=>change("condition",e.target.value)}><MenuItem value="">All conditions</MenuItem>{conditions.map(c=><MenuItem value={c} key={c}>{c}</MenuItem>)}</TextField><TextField select label="Staff filter" value={filters.staff} onChange={e=>change("staff",e.target.value)}><MenuItem value="">All staff</MenuItem>{staff.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField select label="Sort order" value={filters.sort} onChange={e=>change("sort",e.target.value as MonitoringFilters["sort"])}>{view!=="reports"&&<MenuItem value="due">Earliest followup</MenuItem>}<MenuItem value="newest">Newest first</MenuItem><MenuItem value="name">Name A–Z</MenuItem></TextField></div></Collapse>
      <div className="mr-filter-bottom">{chips.map(c=><Chip key={c.key} size="small" label={c.label} onDelete={()=>change(c.key,"")} />)}<Button onClick={reset}>Reset filters</Button></div>{rangeError&&<Alert severity="error">Enter valid dates with the end date on or after the start date.</Alert>}</div>
      <div className="mr-results-heading"><div><Typography component="h2">{view==="followups"?"Scheduled activities":view==="cases"?"Monitoring case directory":"Activity results"}</Typography><Typography variant="body2">{count.toLocaleString()} matching {view==="cases"?"case(s)":"activity record(s)"}</Typography></div><div className="mr-actions"><Button startIcon={<DownloadRounded />} disabled={!count||rangeError} onClick={()=>downloadMonitoringCsv(view,shownCases,shownRows,scope,today)}>Export CSV</Button><Button variant="outlined" startIcon={<PrintOutlined />} disabled={!count||rangeError} onClick={()=>setPrintError(printMonitoring(view,shownCases,shownRows,scope,today)?"":"Allow popups for this page, then select Print records again.")}>Print records</Button></div></div>
      {view==="reports"&&<><div className="mr-report-totals">{[["Recorded activities",totals.visits],["Monitoring cases",totals.cases],["Households identified",totals.households],["Inhabitants monitored",totals.people],["Absent",totals.absent],["Referrals",totals.referred]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><Typography className="mr-report-note" variant="body2">People are counted once from individual cases with recorded results, excluding absent attendance. Household activities do not imply individual attendance or health results. Household totals require a saved household ID; older records may not have one.</Typography>{groups.length>0&&<TableContainer><Table className="mr-table mr-program-table" aria-label="Program summary"><TableHead><TableRow><TableCell>Program</TableCell><TableCell align="right">Activities</TableCell><TableCell align="right">Monitored</TableCell><TableCell align="right">Absent</TableCell><TableCell align="right">Referrals</TableCell></TableRow></TableHead><TableBody>{groups.map(g=><TableRow key={g.program}><TableCell>{g.program}</TableCell><TableCell align="right">{g.visits}</TableCell><TableCell align="right">{g.people}</TableCell><TableCell align="right">{g.absent}</TableCell><TableCell align="right">{g.referred}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}</>}
      {!count?<div className="mr-empty"><EventNoteOutlined /><Typography component="h3">{cases.length?"No records match these filters":"Start your monitoring register"}</Typography><Typography variant="body2">{cases.length?"Adjust the period, program or status to view other records.":"Choose a household, select its members and set the first followups."}</Typography>{cases.length>0&&<Button variant="outlined" onClick={reset}>Reset filters</Button>}</div>:<TableContainer><Table className="mr-table" aria-label={view==="cases"?"Monitoring cases":"Monitoring activities"}>
      {view==="cases"?<><TableHead><TableRow><TableCell>Member or household</TableCell><TableCell>Program / focus</TableCell><TableCell>Assigned staff</TableCell><TableCell>Next followup</TableCell><TableCell>Case status</TableCell><TableCell align="right">Action</TableCell></TableRow></TableHead><TableBody>{shownCases.slice(start,start+pageSize).map(c=><TableRow key={c.id} hover><TableCell><Button className="mr-record-link" onClick={()=>setSelected(c.id)}>{c.person.fullName}</Button><Typography variant="body2">{c.scope==="household"?"Household activity":c.person.householdName} · {c.person.purok||"Purok not recorded"}</Typography></TableCell><TableCell><strong>{c.program}</strong><Typography variant="body2">{c.condition||"General monitoring"}</Typography></TableCell><TableCell>{c.assignedTo}</TableCell><TableCell>{nextDue(c)?dateLabel(nextDue(c)):"None scheduled"}</TableCell><TableCell><MonitoringStatus status={c.status} /></TableCell><TableCell align="right"><Button onClick={()=>setSelected(c.id)}>View case</Button></TableCell></TableRow>)}</TableBody></>:<><TableHead><TableRow><TableCell>Member or household / program</TableCell><TableCell>{view==="reports"?"Actual date / activity":"Scheduled date / activity"}</TableCell><TableCell>{view==="reports"?"Result":"Assigned staff"}</TableCell><TableCell>Attendance</TableCell><TableCell>Status</TableCell><TableCell align="right">Action</TableCell></TableRow></TableHead><TableBody>{shownRows.slice(start,start+pageSize).map(row=>{const {record:c,activity:a}=row,display=view==="reports"?a.context:{person:c.person,program:c.program,assignedTo:c.assignedTo};return <TableRow key={`${c.id}-${a.id}`} hover><TableCell><Button className="mr-record-link" onClick={()=>setSelected(c.id)}>{display.person.fullName}</Button><Typography variant="body2">{display.program} · {c.scope==="household"?"Household activity":display.person.householdName} · {display.person.purok||"Purok not recorded"}</Typography></TableCell><TableCell><strong>{dateLabel(view==="reports"?a.actualDate:a.scheduledDate)}</strong><Typography variant="body2">{a.activityType}</Typography></TableCell><TableCell>{view==="reports"?<Typography className="mr-result-excerpt" title={a.result}>{a.result||"Not recorded"}</Typography>:display.assignedTo}</TableCell><TableCell>{a.attendance||"Not recorded"}</TableCell><TableCell><MonitoringStatus status={a.status} late={view!=="reports"&&overdue(row,today)} /></TableCell><TableCell align="right">{view==="followups"&&a.status==="Pending"&&c.status!=="Completed"?<Button variant="outlined" onClick={()=>setRecordVisit(row)}>Record visit</Button>:<Button onClick={()=>setSelected(c.id)}>View history</Button>}</TableCell></TableRow>;})}</TableBody></>}
      </Table></TableContainer>}
      <TablePagination component="div" count={count} page={safePage} onPageChange={(_,next)=>setPage(next)} rowsPerPage={pageSize} rowsPerPageOptions={[10,25,50]} onRowsPerPageChange={e=>{setPageSize(Number(e.target.value));setPage(0);}} />
      </div>}
    </section>
    {ready&&newCase&&<MonitoringEnrollment programs={catalogPrograms} people={people} households={households} cases={cases} onClose={()=>setNewCase(false)} onSaved={ids=>{setNewCase(false);setView("cases");setFilters({...DEFAULT_MONITORING_FILTERS,sort:"newest"});setPeriod("all");setPage(0);setNotice(`${ids.length} monitoring case(s) and first followups saved.`);}} />}
    {ready&&catalogOpen&&<MonitoringProgramCatalog programs={catalogPrograms} onClose={()=>setCatalogOpen(false)} />}
    {ready&&selectedCase&&<MonitoringDetails programs={catalogPrograms} key={selectedCase.id} record={selectedCase} cases={cases} people={people} households={households} onClose={()=>setSelected("")} onOpenCase={setSelected} />}
    {ready&&recordVisit&&currentVisitCase&&<ActivityForm record={recordVisit.record} activity={recordVisit.activity} mode="Done" onClose={()=>setRecordVisit(null)} onSaved={()=>{setRecordVisit(null);setNotice("Activity result saved.");}} />}
  </div>;
}
