import { downloadCsv } from "./inhabitantExport";
import { activities, context, dateLabel, nextDue, reportGroups, reportTotals, type ActivityRow, type MonitoringCase, type MonitoringFilters } from "../services/monitoringModel";
export type MonitoringView="followups"|"cases"|"reports";
export function filterDescription(f:MonitoringFilters,view:MonitoringView,householdLabel?:string,memberLabel?:string):string[] {
  return [f.household?`Household: ${householdLabel||f.household}`:"",f.member?`Member: ${memberLabel||f.member}`:"",f.scope?`Scope: ${f.scope==="household"?"Household activities":"Individual programs"}`:"",f.search?`Search: ${f.search}`:"",f.program?`Program: ${f.program}`:"All programs",f.condition?`Condition: ${f.condition}`:"",f.purok||"All Puroks",f.staff?`Assigned staff: ${f.staff}`:"",f.status?`Status: ${f.status}`:"All statuses",`${view==="cases"?"Case start dates":view==="reports"||f.dateBasis==="actual"?"Actual activity dates":"Scheduled dates"}: ${f.from?dateLabel(f.from):"Beginning"} to ${f.to?dateLabel(f.to):"Latest"}`].filter(Boolean);
}
export function monitoringCsv(view:MonitoringView,cases:MonitoringCase[],rows:ActivityRow[],scope:string[],date:string):unknown[][] {
  const output:unknown[][]=[[view==="cases"?"Monitoring case directory":view==="reports"?"Monitoring activity report":"Monitoring followup queue"],["Barangay","Bunuanan, Catbalogan City"],["Generated",date],...[...scope].map(s=>[s]),[]];
  if(view==="cases")return [...output,["Case ID","Scope","Household ID","Covered member IDs","Covered members","Inhabitant ID","Name at enrollment","Household at enrollment","Purok at enrollment","Program","Condition / focus","Assigned staff","Start date","Status","Next pending followup","Completion date","Completion result","Case notes"],...cases.map(c=>[c.id,c.scope||"person",c.householdId||c.person.householdId||"",Object.keys(c.participants||{}).join("; "),Object.values(c.participants||{}).map(p=>p.fullName).join("; "),c.inhabitantId,c.person.fullName,c.person.householdName,c.person.purok,c.program,c.condition,c.assignedTo,c.startDate,c.status,nextDue(c),c.completedDate,c.closureNotes,c.notes])];
  if(view==="reports"){
    const totals=reportTotals(rows);
    output.push(["Total activities","Unique cases","Households identified","Individuals monitored","Absent","Referrals"],[totals.visits,totals.cases,totals.households,totals.people,totals.absent,totals.referred],[],["Program","Recorded activities","Inhabitants monitored","Absent","Referrals"],...reportGroups(rows).map(g=>[g.program,g.visits,g.people,g.absent,g.referred]),[]);
  }
  output.push(["Case ID","Activity ID","Scope","Household ID","Covered members","Inhabitant ID","Name on activity record","Household","Purok","Program","Condition / focus","Assigned staff","Activity","Scheduled date","Actual date","Status","Attendance","Observations","Result","Action taken","Referred to","Referral reason","Created by UID","Updated by UID"]);
  rows.forEach(({record,activity:a})=>{const ctx=view==="reports"?a.context:context(record);output.push([record.id,a.id,record.scope||"person",ctx.person.householdId||"",Object.values(ctx.participants||{}).map(p=>p.fullName).join("; "),record.inhabitantId,ctx.person.fullName,ctx.person.householdName,ctx.person.purok,ctx.program,ctx.condition,ctx.assignedTo,a.activityType,a.scheduledDate,a.actualDate,a.status,a.attendance,a.observations,a.result,a.actionTaken,a.referredTo,a.referralReason,a.createdBy,a.updatedBy]);});
  return output;
}
export function downloadMonitoringCsv(view:MonitoringView,cases:MonitoringCase[],rows:ActivityRow[],scope:string[],date:string) {downloadCsv(`Bunuanan_Monitoring_${view}_${date}.csv`,monitoringCsv(view,cases,rows,scope,date));}
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const val=(v:unknown)=>esc(v===""||v==null?"Not recorded":v);
function table(headers:string[],rows:string[][]):string {return `<table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join("")}</tr>`).join(""):`<tr><td colspan="${headers.length}">No records for these filters.</td></tr>`}</tbody></table>`;}
function activityCards(rows:ActivityRow[]):string {return rows.map(({record,activity:a})=>`<article class="activity"><div class="activity-heading"><h2>${esc(a.context.person.fullName)} <span>${esc(a.status)}</span></h2><p>${record.scope==="household"?"Household activity · ":""}${esc(a.context.program)} · ${val(a.context.condition)} · ${val(a.context.person.purok)}</p>${a.context.participants?`<p>Covered members: ${esc(Object.values(a.context.participants).map(p=>p.fullName).join(", "))}</p>`:""}<p><strong>${esc(a.activityType)}</strong> · Scheduled: ${dateLabel(a.scheduledDate)} · Actual: ${dateLabel(a.actualDate)}<br>Attendance: ${val(a.attendance)} · Assigned staff: ${val(a.context.assignedTo)}</p></div>${[["Observations",a.observations],["Result",a.result],["Action taken",a.actionTaken],["Referred to",a.referredTo],["Referral reason",a.referralReason]].filter(([,v])=>Boolean(v)).map(([label,v])=>`<p class="note"><strong>${label}:</strong> ${esc(v)}</p>`).join("")}<p class="record-id">Case ${esc(record.id)} · Activity ${esc(a.id)}</p></article>`).join("");}
export function monitoringPrintHtml(view:MonitoringView|"history",cases:MonitoringCase[],rows:ActivityRow[],scope:string[],date:string):string {
  const title=view==="history"?(cases[0]?.scope==="household"?"Household monitoring history":"Individual monitoring history"):view==="cases"?"Monitoring case directory":view==="reports"?"Monitoring activity report":"Monitoring followup queue";
  let body="";
  if(view==="reports"){
    const totals=reportTotals(rows);body=`<div class="totals"><span><strong>${totals.visits}</strong> recorded activities</span><span><strong>${totals.people}</strong> individuals monitored</span><span><strong>${totals.cases}</strong> unique cases</span><span><strong>${totals.households}</strong> households identified</span><span><strong>${totals.absent}</strong> absent</span><span><strong>${totals.referred}</strong> referrals</span></div>`+table(["Program","Activities","Monitored","Absent","Referrals"],reportGroups(rows).map(g=>[esc(g.program),String(g.visits),String(g.people),String(g.absent),String(g.referred)]))+`<p>Counts use actual activity dates. Individuals are counted once from individual cases, excluding absent attendance. Household activities record shared outcomes and do not imply individual attendance. Household counts exclude earlier records without a saved household ID.</p>`+activityCards(rows);
  }else if(view==="cases")body=table(["Member or household / Purok","Program / focus","Assigned staff","Started","Status","Next followup"],cases.map(c=>[`${esc(c.person.fullName)}<br>${c.scope==="household"?"Household activity":val(c.person.householdName)}<br>${val(c.person.purok)}`,`${esc(c.program)}<br>${val(c.condition)}`,val(c.assignedTo),dateLabel(c.startDate),esc(c.status),dateLabel(nextDue(c))]));
  else if(view==="followups")body=table(["Member or household / Purok","Program","Activity","Scheduled / actual","Status","Assigned staff"],rows.map(({record,activity:a})=>[`${esc(record.person.fullName)}<br>${record.scope==="household"?"Household activity":val(record.person.householdName)}<br>${val(record.person.purok)}`,esc(record.program),esc(a.activityType),`${dateLabel(a.scheduledDate)}<br>${a.actualDate?dateLabel(a.actualDate):"Not yet recorded"}`,`${esc(a.status)}${a.status==="Pending"&&record.status!=="Completed"&&a.scheduledDate<date?" (Overdue)":""}`,val(record.assignedTo)]));
  else {const c=cases[0];if(c)body=`<h2>${esc(c.person.fullName)}</h2><div class="details"><p><strong>Program:</strong> ${esc(c.program)}<br><strong>Condition / focus:</strong> ${val(c.condition)}<br><strong>Assigned staff:</strong> ${val(c.assignedTo)}</p><p><strong>Started:</strong> ${dateLabel(c.startDate)}<br><strong>Case status:</strong> ${esc(c.status)}<br><strong>Next followup:</strong> ${dateLabel(nextDue(c))}</p></div><p><strong>Household at enrollment:</strong> ${val(c.person.householdName)}<br>${val(c.person.purok)} · ${val(c.person.address)}</p>${c.participants?`<p><strong>Covered members:</strong> ${esc(Object.values(c.participants).map(p=>p.fullName).join(", "))}</p>`:""}${c.notes?`<p class="note"><strong>Case notes:</strong> ${esc(c.notes)}</p>`:""}${c.status==="Completed"?`<p class="note"><strong>Completed ${dateLabel(c.completedDate)}:</strong> ${esc(c.closureNotes)}</p>`:""}<h2>Activity history (${activities(c).length})</h2>`+activityCards(rows);}
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | ${esc(date)}</title><style>
  @page{size:A4 ${view==="history"?"portrait":"landscape"};margin:14mm}*{box-sizing:border-box}body{margin:0;color:#111;background:#fff;font:11pt/1.5 Arial,sans-serif}main{max-width:${view==="history"?"182mm":"269mm"};margin:24px auto;padding:0 12px}h1{font-size:20pt;line-height:1.25;margin:0 0 10px}h2{font-size:13pt;margin:18px 0 8px;break-after:avoid}h2 span{font-size:11pt;font-weight:400;margin-left:12px}p{margin:6px 0 12px;overflow-wrap:anywhere;orphans:3;widows:3}.scope{border:1px solid #777;padding:10px 12px;margin:18px 0}.totals,.details{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.totals strong{font-size:15pt}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:16px 0 22px}th,td{border:1px solid #777;padding:8px;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#e7ebef;font-weight:700}thead{display:table-header-group;break-inside:avoid}tr{break-inside:avoid}.activity{break-inside:avoid;page-break-inside:avoid;border-top:1px solid #555;padding:4px 0 12px;margin:18px 0}.activity-heading{break-inside:avoid;break-after:avoid}.note{white-space:pre-wrap}.record-id{font-size:11pt;color:#444}.controls{font:16px/1.5 Arial,sans-serif;background:#f1f4f7;padding:16px 24px;border-bottom:1px solid #ccc}.controls button{font:600 16px/1.5 Arial,sans-serif;padding:10px 20px;background:#0b5ed7;border:0;border-radius:6px;color:white;cursor:pointer}.controls span{margin-left:14px}@media print{main{margin:0;max-width:none;padding:0}.controls{display:none}}@media screen and (max-width:700px){main{min-width:660px;margin:20px 0}}
  </style></head><body><div class="controls"><button id="print" type="button">Print / Save as PDF</button><span>A4 ${view==="history"?"portrait":"landscape"} · Use Actual size or 100% scale.</span></div><main><h1>${esc(title)}</h1><p>Barangay Bunuanan · City of Catbalogan · Samar · Region VIII<br>Generated ${dateLabel(date)}</p><div class="scope">${scope.map(esc).join(" · ")}</div>${body}</main></body></html>`;
}
export function printMonitoring(view:MonitoringView|"history",cases:MonitoringCase[],rows:ActivityRow[],scope:string[],date:string):boolean {
  const win=window.open("","_blank","width=1200,height=900");if(!win)return false;
  try{win.document.open();win.document.write(monitoringPrintHtml(view,cases,rows,scope,date));win.document.close();win.document.getElementById("print")?.addEventListener("click",()=>win.print());win.focus();return true;}catch{win.close();return false;}
}
